version: '3.1'

services:
  db:
    image: mysql:8.0.36-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: parcela123
      MYSQL_DATABASE: parcela
      MYSQL_USER: user
      MYSQL_PASSWORD: parcela123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    cap_add:
      - SYS_PTRACE

volumes:
  db_data:
